spring:
 profiles:
  active: @activatedProperties@
 thymeleaf:
   check-template-location: true # Check that the templates location exists.
   content-type: text/html # Content-Type value.
   enabled: true # Enable MVC Thymeleaf view resolution.
   encoding: UTF-8 # Template encoding.
   excluded-view-names:  # Comma-separated list of view names that should be excluded from resolution.
   mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
   prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
   suffix: .html
   cache: false
# Suffix that gets appended to view names when building a URL.
#     template-resolver-order:  # Order of the template resolver in the chain.
#     view-names:  # Comma-separated list of view names that can be resolved.
 mvc:
  favicon:
    enabled: false
 http:
   multipart:
     max-file-size: 2MB
     max-request-size: 2MB
server:
    context-path: /@project.name@

cache:
  expireTime: 3600  # expire time in seconds
